% LINEAR CONVOLUTION_2
t_min=0;
t_max=10;
t=t_min:0.01:t_max;
x1=1.*(t>=1&t<=10);
x2=1.*(t>=2&t<=10);
subplot(3,1,1);
plot(t,x1,'r');
xlabel('Continuous Time(t)--->');
ylabel('Amplitude of x1(t)--->');
title('Continuous Time Signal [x1(t)=1]');
grid on;
subplot(3,1,2);
plot(t,x2,'g');
xlabel('Continuous Time(t)--->');
ylabel('Amplitude of x2(t)--->');
title('Continuous Time Signal [x2(t)=1]');
grid on;
y=conv(x1,x2);
n1=length(y);
t1=0:1:(n1-1);
subplot(3,1,3);
plot(t1,y,'m');
xlim([0 600]);
xlabel('Time (dt)--->');
ylabel('Amplitude y(t)dt--->');
title('Convolution of x(t)*h(t)=y(t)');
grid on;
